server:
  port: 8800 # 指定服务运行的端口号
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource #指定数据库连接池
    driver-class-name: com.mysql.cj.jdbc.Driver #指定MySQL数据库驱动
    url: jdbc:mysql://localhost:3306/guigu-oa?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true #指定数据库url，必须指定时区
    username: root #用户
    password: 123456 #密码

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    password:
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲

  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: full
    check-process-definitions: true

knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: sunruolifeng@gamil.com
    concat: sunjianrong
    url: https://rlfit.cn
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 测试用户接口
        api-rule: package
        api-rule-resources:
          - cn.rlfit
